export HF_ENDPOINT=https://hf-mirror.com
export MODEL_NAME='runwayml/stable-diffusion-v1-5' # pre-trained sd dir
export CKPT_RANK='../code/output/Pororo/pipeline' # The trained ckpt dir of the customized story world
export STORY_TXT_DIR='../TBC_Bench/eval-plot/eval_new_story/Pororo_the_Little_Penguin/Multi/all/1.txt' # story txt path, taking Pororo as an example
export SCALE='2.5' # time-aware scale
export SAMPLE_DIR='sample' # output dir for the generated images
export MAX_CHAR=2 # max number of character in per scene
export CHAR_CAP='../TBC_Bench/train-folder/Pororo_the_Little_Penguin/character' # txt dir for appearance description for character, taking Pororo as an example
export STYLE_DIR='../TBC_Bench/train-folder/Pororo_the_Little_Penguin/style.txt'
export DATA_NAME='Pororo'
CUDA_VISIBLE_DEVICES=4 accelerate launch sample.py  \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --dataset_dir=$STORY_TXT_DIR \
  --style_dir=$STYLE_DIR \
  --resolution=512 \
  --output_dir=$SAMPLE_DIR \
  --seed=42 \
  --max_char=$MAX_CHAR \
  --caption_dir=$CHAR_CAP \
  --ckpt_rank=$CKPT_RANK \
  --seed_num=1 \
  --scale=$SCALE \
  --data_name=$DATA_NAME \
