export MODEL_NAME='runwayml/stable-diffusion-v1-5' # pre-trained sd dir
export CKPT_RANK='' # The trained ckpt dir of the customized story world
export STORY_TXT_DIR='TBC_Benchmark/eval-plot/eval_new_story/Pororo_the_Little_Penguin/Multi/all/1.txt' # story txt path, taking Pororo as an example
export SCALE='2.5' # time-aware scale
export SAMPLE_DIR='' # output dir for the generated images
export MAX_CHAR=2 # max number of character in per scene
export CHAR_CAP='TBC_Benchmark/train-folder/Pororo_the_Little_Penguin/character' # txt dir for appearance description for character, taking Pororo as an example
accelerate launch sample.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --dataset_dir=$STORY_TXT_DIR \
  --resolution=512 \
  --output_dir=$SAMPLE_DIR \
  --seed=42 \
  --mask_maker_dir=$MASK_MAKER \
  --max_char=$MAX_CHAR \
  --caption_dir=$CHAR_CAP \
  --ckpt_rank=$CKPT_RANK \
  --seed_num=1 \
  --scale=$SCALE \
